#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 011-fix-ci

set -e

echo "========================================"
echo "Setup: Fix CI Workflows"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY RUST TOOLCHAIN
# ============================================

echo ""
echo "Checking Rust toolchain..."

if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found${NC}"
    echo "Install Rust from https://rustup.rs/"
    exit 1
fi

if ! command -v rustc &> /dev/null; then
    echo -e "${RED}ERROR: rustc not found${NC}"
    echo "Install Rust from https://rustup.rs/"
    exit 1
fi

CARGO_VERSION=$(cargo --version)
RUSTC_VERSION=$(rustc --version)

echo -e "${GREEN}✓${NC} cargo: $CARGO_VERSION"
echo -e "${GREEN}✓${NC} rustc: $RUSTC_VERSION"

# ============================================
# VERIFY RUST COMPONENTS
# ============================================

echo ""
echo "Checking Rust components..."

if ! cargo clippy --version &> /dev/null; then
    echo -e "${YELLOW}WARNING: clippy not found, installing...${NC}"
    rustup component add clippy
fi

if ! cargo fmt --version &> /dev/null; then
    echo -e "${YELLOW}WARNING: rustfmt not found, installing...${NC}"
    rustup component add rustfmt
fi

echo -e "${GREEN}✓${NC} clippy: $(cargo clippy --version)"
echo -e "${GREEN}✓${NC} rustfmt: $(cargo fmt --version)"

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo "Verifying project structure..."

if [ ! -f "Cargo.toml" ]; then
    echo -e "${RED}ERROR: Cargo.toml not found${NC}"
    echo "Run this script from the project root"
    exit 1
fi

if [ ! -f "Makefile" ]; then
    echo -e "${RED}ERROR: Makefile not found${NC}"
    exit 1
fi

if [ ! -d ".github/workflows" ]; then
    echo -e "${RED}ERROR: .github/workflows directory not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Cargo.toml found"
echo -e "${GREEN}✓${NC} Makefile found"
echo -e "${GREEN}✓${NC} .github/workflows directory found"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Delete .github/workflows/ai-coding-job.yml"
echo "  2. Create .github/workflows/ci.yml"
echo "  3. Audit repo-health.yml and release.yml"
echo "  4. Add CI badge to README.md"
echo "  5. Run 'make check' to verify"
echo ""
echo "To start the coder agent:"
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 011 --parallel 1"
echo ""
