#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 014

set -e

echo "========================================"
echo "Spec 014: Verify make check & install-hooks"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo "Checking build environment..."

# Verify we're in the bop project root
if [ ! -f "Cargo.toml" ] || [ ! -d "crates/bop-cli" ]; then
    echo -e "${RED}Error: Not in bop project root${NC}"
    exit 1
fi

# Verify cargo is available
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found in PATH${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Environment ready${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop..."
cargo build --quiet
echo -e "${GREEN}✓ Build complete${NC}"

# ============================================
# VERIFICATION TASKS
# ============================================

echo ""
echo "This spec performs verification only."
echo "The coder agent will:"
echo "  1. Run 'make check' (test + clippy + fmt)"
echo "  2. Verify install_hooks_linux implementation"
echo "  3. Create output/result.md with results"
echo ""
echo "No services need to be started."
echo ""

# ============================================
# SUMMARY
# ============================================

echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Run coder agent with:"
echo "  source .auto-claude/.venv/bin/activate"
echo "  python .auto-claude/backend/run.py --spec 014 --direct"
echo ""
