#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 007: bop clean command

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check prerequisites
echo "Checking prerequisites..."

# Check for Rust toolchain
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found. Please install Rust toolchain.${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain found${NC}"

# Check for required crates
if ! command -v rustfmt &> /dev/null; then
    echo -e "${YELLOW}Warning: rustfmt not found. Installing...${NC}"
    rustup component add rustfmt
fi

if ! command -v clippy-driver &> /dev/null; then
    echo -e "${YELLOW}Warning: clippy not found. Installing...${NC}"
    rustup component add clippy
fi

# Verify project structure
if [ ! -f "Cargo.toml" ]; then
    echo -e "${RED}Error: Cargo.toml not found. Are you in the project root?${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Project structure verified${NC}"

# Build the project to ensure dependencies are fetched
echo ""
echo "Building project (this may take a moment on first run)..."
cargo build
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# Run tests to ensure baseline passes
echo ""
echo "Running existing tests..."
cargo test --quiet
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Existing tests pass${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed (expected for new implementation)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "You can now implement the bop clean command."
echo ""
echo "Quick commands:"
echo "  Build:       cargo build"
echo "  Test:        cargo test"
echo "  Lint:        cargo clippy -- -D warnings"
echo "  Format:      cargo fmt"
echo "  Check all:   make check"
echo ""
echo "Binary location: ./target/debug/bop"
echo "To test: ./target/debug/bop clean --help"
echo ""
