#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 001

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get project root (script is in .auto-claude/specs/001-create-test-real-adapters-script/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "Project root: $PROJECT_ROOT"
cd "$PROJECT_ROOT"

# ============================================
# BUILD BOP BINARY
# ============================================

echo ""
echo "Building bop binary..."
if cargo build; then
    echo -e "${GREEN}✓ bop binary built${NC}"
else
    echo -e "${RED}✗ Failed to build bop binary${NC}"
    exit 1
fi

# Verify binary exists
BOP_BIN="$PROJECT_ROOT/target/debug/bop"
if [ -f "$BOP_BIN" ]; then
    echo -e "${GREEN}✓ Binary found at: $BOP_BIN${NC}"
else
    echo -e "${RED}✗ Binary not found at: $BOP_BIN${NC}"
    exit 1
fi

# ============================================
# CHECK NUSHELL AVAILABILITY
# ============================================

echo ""
echo "Checking Nushell availability..."
if command -v nu &> /dev/null; then
    NU_VERSION=$(nu --version)
    echo -e "${GREEN}✓ Nushell available: $NU_VERSION${NC}"
else
    echo -e "${YELLOW}⚠ Nushell not found in PATH${NC}"
    echo "Install with: brew install nushell"
fi

# ============================================
# CHECK ADAPTER DEPENDENCIES (OPTIONAL)
# ============================================

echo ""
echo "Checking adapter dependencies (optional)..."

if command -v claude &> /dev/null; then
    echo -e "${GREEN}✓ claude CLI available${NC}"
else
    echo -e "${YELLOW}⊘ claude CLI not found (tests will skip)${NC}"
fi

if command -v ollama &> /dev/null; then
    echo -e "${GREEN}✓ ollama CLI available${NC}"
    if curl -sf http://localhost:11434/api/tags &> /dev/null; then
        echo -e "${GREEN}✓ ollama service running${NC}"
    else
        echo -e "${YELLOW}⊘ ollama service not running (tests will skip)${NC}"
    fi
else
    echo -e "${YELLOW}⊘ ollama not found (tests will skip)${NC}"
fi

if command -v codex &> /dev/null; then
    echo -e "${GREEN}✓ codex CLI available${NC}"
    if [ -n "${OPENAI_API_KEY}" ]; then
        echo -e "${GREEN}✓ OPENAI_API_KEY set${NC}"
    else
        echo -e "${YELLOW}⊘ OPENAI_API_KEY not set (tests will skip)${NC}"
    fi
else
    echo -e "${YELLOW}⊘ codex not found (tests will skip)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Implement scripts/test-real-adapters.nu"
echo "  2. Run self-tests: nu --no-config-file scripts/test-real-adapters.nu --test"
echo "  3. Run adapter tests: nu --no-config-file scripts/test-real-adapters.nu"
echo "  4. Verify: make check"
echo ""
