#!/bin/bash

# Auto-Build Environment Setup — Spec 030: bop providers scaffold + Claude OAuth
# Generated by Planner Agent

set -e

echo "========================================"
echo "Spec 030: bop providers scaffold"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/Users/studio/bop"

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Pre-flight checks..."

# Check Rust toolchain
if ! command -v cargo &>/dev/null; then
    echo -e "${RED}cargo not found — install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}✓ cargo$(cargo --version | awk '{print " "$2}')${NC}"

# Check that we're in the right directory
if [ ! -f "$PROJECT_DIR/Cargo.toml" ]; then
    echo -e "${RED}Not in bop project root${NC}"
    exit 1
fi
echo -e "${GREEN}✓ bop workspace found${NC}"

# Check crate structure
if [ ! -f "$PROJECT_DIR/crates/bop-cli/Cargo.toml" ]; then
    echo -e "${RED}crates/bop-cli/Cargo.toml missing${NC}"
    exit 1
fi
echo -e "${GREEN}✓ bop-cli crate present${NC}"

# Check existing providers.rs
if [ ! -f "$PROJECT_DIR/crates/bop-cli/src/providers.rs" ]; then
    echo -e "${YELLOW}⚠ providers.rs not found — may already be converted to providers/mod.rs${NC}"
    if [ -f "$PROJECT_DIR/crates/bop-cli/src/providers/mod.rs" ]; then
        echo -e "${GREEN}✓ providers/mod.rs already exists${NC}"
    fi
else
    echo -e "${GREEN}✓ providers.rs exists (will be converted to directory module)${NC}"
fi

# ============================================
# BUILD CHECK
# ============================================

echo ""
echo "Running initial build check..."

cd "$PROJECT_DIR"
if cargo check -p bop 2>&1 | tail -1 | grep -q "Finished"; then
    echo -e "${GREEN}✓ cargo check passes${NC}"
else
    echo -e "${RED}cargo check failed — fix build errors first${NC}"
    cargo check -p bop 2>&1 | tail -5
    exit 1
fi

# ============================================
# TEST BASELINE
# ============================================

echo ""
echo "Running test baseline..."

if cargo test -p bop -- providers:: 2>&1 | tail -3 | grep -q "test result: ok"; then
    echo -e "${GREEN}✓ existing provider tests pass${NC}"
else
    echo -e "${YELLOW}⚠ some provider tests may have failed — check output${NC}"
    cargo test -p bop -- providers:: 2>&1 | tail -5
fi

# ============================================
# CREDENTIAL CHECK (informational)
# ============================================

echo ""
echo "Checking Claude credentials (informational)..."

CREDS_FILE="$HOME/.claude/.credentials.json"
if [ -f "$CREDS_FILE" ]; then
    echo -e "${GREEN}✓ ~/.claude/.credentials.json found${NC}"
    echo "  (OAuth fetch will work during testing)"
else
    echo -e "${YELLOW}ℹ ~/.claude/.credentials.json not found${NC}"
    echo "  (detect() will return false; --json will output empty array)"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project:  $PROJECT_DIR"
echo "Crate:    bop-cli (crates/bop-cli/)"
echo ""
echo "Key files to create/modify:"
echo "  crates/bop-cli/Cargo.toml           — add reqwest, async-trait"
echo "  crates/bop-cli/src/providers/mod.rs  — refactored from providers.rs + new types"
echo "  crates/bop-cli/src/providers/claude.rs — Claude OAuth provider"
echo "  crates/bop-cli/src/providers/history.rs — JSONL history tracking"
echo "  crates/bop-cli/src/main.rs           — add Providers subcommand"
echo ""
echo "Verify with:"
echo "  cargo build -p bop && cargo test -p bop -- providers"
echo "  cargo clippy -- -D warnings && cargo fmt --check"
echo ""
