#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 017

set -e

echo "========================================"
echo "Quick Look Zellij Links + Log Tail"
echo "Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY TOOLS
# ============================================

echo ""
echo "Verifying development tools..."

# Check Rust/Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}❌ cargo not found${NC}"
    echo "Install Rust: https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ cargo found: $(cargo --version)${NC}"

# Check xcodebuild (for Swift compilation)
if ! command -v xcodebuild &> /dev/null; then
    echo -e "${RED}❌ xcodebuild not found${NC}"
    echo "Install Xcode Command Line Tools: xcode-select --install"
    exit 1
fi
echo -e "${GREEN}✓ xcodebuild found${NC}"

# Check we're in the right directory
if [ ! -f "Cargo.toml" ] || [ ! -d "macos" ]; then
    echo -e "${RED}❌ Not in bop project root${NC}"
    echo "Current directory: $(pwd)"
    echo "Expected: /Users/studio/bop"
    exit 1
fi
echo -e "${GREEN}✓ Project structure verified${NC}"

# ============================================
# PROJECT STATUS
# ============================================

echo ""
echo "========================================"
echo "Project Ready"
echo "========================================"
echo ""
echo "Services:"
echo "  • Rust workspace (crates/bop-cli)"
echo "  • macOS Quick Look (macos/)"
echo ""
echo "Key files:"
echo "  • crates/bop-cli/src/dispatcher.rs"
echo "  • macos/bop/PreviewViewController.swift"
echo ""
echo "Build commands:"
echo "  • Rust: cargo build --package bop-cli"
echo "  • Swift: xcodebuild -project macos/macos.xcodeproj -scheme JobCardHost -configuration Debug build"
echo ""
echo "Test commands:"
echo "  • Rust tests: cargo test --package bop-cli"
echo ""
echo -e "${GREEN}Ready to implement!${NC}"
echo ""
