#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 003 - Claude E2E Adapter Test"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check for Rust/Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found. Install Rust from https://rustup.rs/${NC}"
    exit 1
fi
echo -e "${GREEN}✓ cargo found${NC}"

# Check for Nushell
if ! command -v nu &> /dev/null; then
    echo -e "${RED}ERROR: nu (nushell) not found. Install with: brew install nushell${NC}"
    exit 1
fi
echo -e "${GREEN}✓ nushell found${NC}"

# Check for Claude CLI
if ! command -v claude &> /dev/null; then
    echo -e "${YELLOW}WARNING: claude CLI not found. Test will fail without it.${NC}"
    echo -e "${YELLOW}Install from: https://github.com/anthropics/claude-cli${NC}"
else
    echo -e "${GREEN}✓ claude CLI found at $(which claude)${NC}"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop binary..."
cargo build

if [ ! -f "target/debug/bop" ]; then
    echo -e "${RED}ERROR: bop binary not created${NC}"
    exit 1
fi
echo -e "${GREEN}✓ bop binary built successfully${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "Binary:  target/debug/bop"
echo "Test:    scripts/test-real-adapters.nu"
echo ""
echo "To run the test manually:"
echo "  nu --no-config-file scripts/test-real-adapters.nu --adapter claude --timeout 120"
echo ""
echo "To run full checks:"
echo "  make check"
echo ""
