#!/bin/bash

# Auto-Build Environment Setup for spec 015
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop project..."
cargo build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# VERIFY CARGO TEST WORKS
# ============================================

echo ""
echo "Verifying cargo test works..."
cargo test -p bop --lib --no-fail-fast 2>&1 | head -20

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "Binary: target/debug/bop"
echo "Test command: cargo test -p bop"
echo "Lint command: cargo clippy -- -D warnings"
echo "Full check: make check"
echo ""
echo "Next steps:"
echo "  1. Implement serve_smoke.rs integration test"
echo "  2. Run: cargo test -p bop test_serve_smoke"
echo "  3. Run: make check"
echo ""
