#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 009

set -e

echo "========================================"
echo "Event-driven merge-gate Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Rust/Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found${NC}"
    echo "Install Rust: https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ cargo found${NC}"

# Check xmllint (for macOS plist validation)
if command -v xmllint &> /dev/null; then
    echo -e "${GREEN}✓ xmllint found (plist validation available)${NC}"
else
    echo -e "${YELLOW}⚠ xmllint not found (plist validation will be skipped)${NC}"
fi

# ============================================
# BUILD
# ============================================

echo ""
echo "Building bop binary..."
cargo build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# PLATFORM INFO
# ============================================

echo ""
echo "========================================"
echo "Platform Information"
echo "========================================"
echo "OS: $(uname -s)"
echo "Architecture: $(uname -m)"

if [[ "$(uname -s)" == "Darwin" ]]; then
    echo "Service Manager: launchd"
    echo "Installation Path: ~/Library/LaunchAgents/"
elif [[ "$(uname -s)" == "Linux" ]]; then
    echo "Service Manager: systemd"
    echo "Installation Path: ~/.config/systemd/user/"
else
    echo -e "${YELLOW}⚠ Unknown platform - installation may not work${NC}"
fi

# ============================================
# READY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Implement the subtasks in implementation_plan.json"
echo "  2. Test with: ./target/debug/bop install-hooks"
echo "  3. Verify with: make check"
echo ""
echo "Implementation Progress:"
echo "  Phase 1: Create service template files"
echo "  Phase 2: Implement install-hooks command"
echo "  Phase 3: Integration testing"
echo ""
