#!/bin/bash

# Auto-Build Environment Setup for Spec 004: Codex E2E Adapter Test
# Generated by Planner Agent

set -e

echo "========================================"
echo "Codex Adapter Test Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Nushell
if ! command -v nu &> /dev/null; then
    echo -e "${RED}ERROR: Nushell (nu) not found${NC}"
    echo "Install: brew install nushell"
    exit 1
fi
echo -e "${GREEN}✓ Nushell installed${NC}"

# Check Rust/Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: Cargo not found${NC}"
    echo "Install: https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ Cargo installed${NC}"

# Check if codex CLI is installed
if command -v codex &> /dev/null; then
    CODEX_VERSION=$(codex --version 2>&1 || echo "unknown")
    echo -e "${GREEN}✓ Codex CLI installed: $CODEX_VERSION${NC}"
else
    echo -e "${YELLOW}⊘ Codex CLI not installed (test will skip)${NC}"
    echo "  Install: brew install codex"
fi

# Check OPENAI_API_KEY
if [ -n "$OPENAI_API_KEY" ]; then
    echo -e "${GREEN}✓ OPENAI_API_KEY is set${NC}"
    echo "  Codex test will RUN (may incur API costs)"
else
    echo -e "${YELLOW}⊘ OPENAI_API_KEY not set (test will skip)${NC}"
    echo "  Set with: export OPENAI_API_KEY=sk-..."
fi

# ============================================
# BUILD BOP BINARY
# ============================================

echo ""
echo "Building bop binary..."
if cargo build; then
    echo -e "${GREEN}✓ bop binary built${NC}"
else
    echo -e "${RED}ERROR: Failed to build bop${NC}"
    exit 1
fi

# ============================================
# VERIFY TEST SCRIPT EXISTS
# ============================================

echo ""
echo "Verifying test infrastructure..."

if [ ! -f "scripts/test-real-adapters.nu" ]; then
    echo -e "${RED}ERROR: scripts/test-real-adapters.nu not found${NC}"
    echo "This file should exist from spec 001"
    exit 1
fi
echo -e "${GREEN}✓ Test script exists${NC}"

if [ ! -f "adapters/codex.nu" ]; then
    echo -e "${RED}ERROR: adapters/codex.nu not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Codex adapter exists${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Test command:"
echo "  nu --no-config-file scripts/test-real-adapters.nu --adapter codex --timeout 120"
echo ""
echo "Expected outcomes:"
echo "  - If OPENAI_API_KEY is set: Test should PASS (✓ codex: PASS)"
echo "  - If OPENAI_API_KEY is not set: Test should SKIP (⊘ codex — skipped)"
echo "  - Either outcome is acceptable per spec"
echo ""
