#!/bin/bash

# Auto-Build Environment Setup - Dogfood Seed
# Generated by Planner Agent

set -e

echo "========================================"
echo "Dogfood Seed - Environment Check"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if we're in the right directory
if [ ! -f "Cargo.toml" ] || [ ! -d ".cards" ]; then
    echo -e "${RED}Error: Must run from bop project root${NC}"
    exit 1
fi

# Check cargo is available
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found${NC}"
    exit 1
fi

# Check jq is available (for verification commands)
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq not found (needed for card verification)${NC}"
    exit 1
fi

# Build bop binary
echo ""
echo "Building bop binary..."
cargo build --bin bop

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# Check current pending cards
echo ""
echo "Current pending cards:"
./target/debug/bop list --state pending 2>/dev/null || echo "(none)"

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This task will create 7 cards across 4 teams."
echo "Run the coder agent to execute the implementation plan."
echo ""
