#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 018

set -e

echo "========================================"
echo "CLI UX Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY RUST TOOLCHAIN
# ============================================

echo "Checking Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}cargo not found - please install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}✓ cargo found${NC}"

if ! command -v rustfmt &> /dev/null; then
    echo -e "${RED}rustfmt not found - install with: rustup component add rustfmt${NC}"
    exit 1
fi
echo -e "${GREEN}✓ rustfmt found${NC}"

if ! command -v clippy-driver &> /dev/null; then
    echo -e "${RED}clippy not found - install with: rustup component add clippy${NC}"
    exit 1
fi
echo -e "${GREEN}✓ clippy found${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop workspace..."
cargo build --workspace
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS (baseline)
# ============================================

echo ""
echo "Running baseline tests..."
cargo test -p bop-cli --lib
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Tests passing${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failing (will fix during implementation)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Development commands:"
echo "  cargo build            - Build the project"
echo "  cargo test -p bop-cli  - Run tests"
echo "  cargo clippy           - Lint check"
echo "  cargo fmt              - Format code"
echo "  make check             - Run all checks (test + clippy + fmt)"
echo ""
echo "Testing CLI changes:"
echo "  cargo run --bin bop -- list --state all"
echo "  cargo run --bin bop -- status"
echo "  cargo run --bin bop -- new test-template test-id"
echo ""
