#!/bin/bash
# Auto-Build Environment Setup for QEMU Adapter
# Generated by Planner Agent

set -e

echo "========================================"
echo "QEMU Adapter Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Rust toolchain
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}✗ Rust toolchain not found${NC}"
    echo "  Install from: https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain available${NC}"

# Check Nushell
if ! command -v nu &> /dev/null; then
    echo -e "${RED}✗ Nushell not found${NC}"
    echo "  Install with: brew install nushell"
    exit 1
fi
echo -e "${GREEN}✓ Nushell available${NC}"

# Check QEMU
if ! command -v qemu-system-x86_64 &> /dev/null; then
    echo -e "${YELLOW}⚠ QEMU not found${NC}"
    echo "  Install with: brew install qemu"
    echo "  Adapter will still be created but won't run until QEMU is installed"
else
    echo -e "${GREEN}✓ QEMU available: $(which qemu-system-x86_64)${NC}"
fi

# Check zam (expected to not be built yet)
ZAM_IMAGE="/Users/studio/zam/target/zam.elf"
if [ -f "$ZAM_IMAGE" ]; then
    echo -e "${GREEN}✓ zam image found: $ZAM_IMAGE${NC}"
else
    echo -e "${YELLOW}⚠ zam image not built yet${NC}"
    echo "  Expected at: $ZAM_IMAGE"
    echo "  Adapter will fail gracefully until zam is available"
    echo "  Build zam with: cd /Users/studio/zam && cargo build --release"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop project..."

if cargo build; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running existing tests..."

if cargo test --quiet; then
    echo -e "${GREEN}✓ Tests passed${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed${NC}"
    echo "  This is expected if working on new features"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop QEMU adapter"
echo "Binary:  ./target/debug/bop"
echo "Adapters: ./adapters/"
echo ""
echo "Next steps:"
echo "  1. Implement adapters/qemu.nu"
echo "  2. Add self-tests with --test flag"
echo "  3. Create adapters/README.md"
echo "  4. Verify with: make check"
echo ""
echo "When zam is available:"
echo "  - Full VM execution will work"
echo "  - Until then, adapter fails gracefully"
echo ""
