#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 002: Ollama E2E Adapter Test

set -e

echo "========================================"
echo "Ollama Adapter E2E Test - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Ollama is running
if ! curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
    echo -e "${RED}ERROR: Ollama server is not running${NC}"
    echo "Please start Ollama:"
    echo "  brew services start ollama"
    echo "  OR"
    echo "  ollama serve"
    exit 1
fi
echo -e "${GREEN}✓ Ollama server is running${NC}"

# Check if qwen2.5:7b model is available
if ! ollama list | grep -q "qwen2.5:7b"; then
    echo -e "${YELLOW}WARNING: Model qwen2.5:7b not found${NC}"
    echo "Pulling model (this may take several minutes)..."
    ollama pull qwen2.5:7b
    if [ $? -ne 0 ]; then
        echo -e "${RED}ERROR: Failed to pull qwen2.5:7b model${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}✓ Model qwen2.5:7b is available${NC}"

# Check if Nushell is available
if ! command -v nu >/dev/null 2>&1; then
    echo -e "${RED}ERROR: Nushell (nu) is not installed${NC}"
    echo "Please install Nushell:"
    echo "  brew install nushell"
    exit 1
fi
echo -e "${GREEN}✓ Nushell is available${NC}"

# Check if Rust/Cargo is available
if ! command -v cargo >/dev/null 2>&1; then
    echo -e "${RED}ERROR: Cargo is not installed${NC}"
    echo "Please install Rust:"
    echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi
echo -e "${GREEN}✓ Cargo is available${NC}"

# ============================================
# BUILD BOP BINARY
# ============================================

echo ""
echo "Building bop binary..."
cargo build
if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: Failed to build bop binary${NC}"
    exit 1
fi
echo -e "${GREEN}✓ bop binary built successfully${NC}"

# ============================================
# VERIFY TEST SCRIPT EXISTS
# ============================================

if [ ! -f "scripts/test-real-adapters.nu" ]; then
    echo -e "${RED}ERROR: scripts/test-real-adapters.nu not found${NC}"
    echo "This file should have been created by spec 001"
    exit 1
fi
echo -e "${GREEN}✓ test-real-adapters.nu exists${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Prerequisites met:"
echo "  - Ollama server running at http://localhost:11434"
echo "  - Model qwen2.5:7b available"
echo "  - Nushell $(nu --version | head -1)"
echo "  - Cargo $(cargo --version)"
echo "  - bop binary built at target/debug/bop"
echo ""
echo "Next steps:"
echo "  1. Fix adapters/ollama-local.nu (add fallback after line 111)"
echo "  2. Run: OLLAMA_MODEL=qwen2.5:7b nu --no-config-file scripts/test-real-adapters.nu --adapter ollama --timeout 180"
echo "  3. Run: make check"
echo ""
