#!/bin/bash

# Auto-Build Environment Setup for Spec 020
# Generated by Planner Agent

set -e

echo "========================================"
echo "Event-Driven Dispatcher Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Verify we're in the bop project root
if [ ! -f "Cargo.toml" ] || [ ! -d "crates/bop-cli" ]; then
    echo -e "${RED}ERROR: Not in bop project root${NC}"
    echo "Expected Cargo.toml and crates/bop-cli to exist"
    exit 1
fi

# Check for cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found${NC}"
    echo "Please install Rust: https://rustup.rs/"
    exit 1
fi

# Check for nu (Nushell) - used by adapters
if ! command -v nu &> /dev/null; then
    echo -e "${YELLOW}WARNING: nu (Nushell) not found${NC}"
    echo "Adapters may fail. Install with: brew install nushell"
fi

echo ""
echo "========================================"
echo "Building Project"
echo "========================================"
echo ""

# Clean build to ensure dependencies are fresh
cargo clean
cargo fetch

# Build the project
echo "Building bop-cli..."
cargo build -p bop

# Run a quick test to verify it works
echo ""
echo "Running quick verification..."
cargo test -p bop --lib -- --test-threads=1 2>&1 | head -20

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (event-driven dispatcher)"
echo "Binary:  target/debug/bop"
echo ""
echo "Key Commands:"
echo "  make check          - Run all checks (test + clippy + fmt)"
echo "  cargo test -p bop   - Run all tests"
echo "  cargo build         - Build debug binary"
echo "  cargo build --release - Build optimized binary"
echo ""
echo "Files to Modify:"
echo "  - crates/bop-cli/src/dispatcher.rs (polling → events)"
echo "  - crates/bop-cli/src/merge_gate.rs (polling → events)"
echo "  - crates/bop-cli/Cargo.toml (add notify-debouncer-mini)"
echo "  - Cargo.toml (release profile optimization)"
echo ""
echo "Reference Pattern:"
echo "  - crates/bop-cli/src/icons.rs (existing notify usage)"
echo ""
