#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 019-serve-security-hardening

set -e

echo "========================================"
echo "bop serve Security Hardening Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Verify we're in the bop project root
if [ ! -f "Cargo.toml" ] || [ ! -d "crates/bop-cli" ]; then
    echo -e "${RED}Error: Must run from bop project root${NC}"
    exit 1
fi

echo ""
echo "Checking Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}cargo not found - install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain available${NC}"

echo ""
echo "Checking project builds..."
if cargo check --package bop 2>&1 | grep -q "Finished"; then
    echo -e "${GREEN}✓ Project compiles${NC}"
else
    echo -e "${RED}✗ Project has compile errors${NC}"
    echo "Running cargo check for details:"
    cargo check --package bop
    exit 1
fi

echo ""
echo "Creating output directory..."
mkdir -p output
echo -e "${GREEN}✓ output/ directory ready${NC}"

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust CLI tool)"
echo "Crate: bop-cli (crates/bop-cli/)"
echo "Target file: crates/bop-cli/src/serve.rs"
echo ""
echo "Available commands:"
echo "  cargo test --package bop          - Run tests"
echo "  cargo clippy --package bop        - Run linter"
echo "  cargo fmt                         - Format code"
echo "  make check                        - Run all checks (test + clippy + fmt)"
echo ""
echo "Security fixes to implement:"
echo "  1. Constant-time token comparison (subtle crate)"
echo "  2. Mandatory authentication (generate token if unset)"
echo "  3. Request body size limit (64 KiB max)"
echo "  4. Enhanced card ID sanitization (reject .., %, null bytes)"
echo "  5. Security response headers middleware"
echo "  6. Rate limiting (10 req/min per IP)"
echo "  7. Verification + result.md documentation"
echo ""
echo "Ready to begin implementation!"
echo ""
