#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 006-job-control-retry-kill-logs

set -e

echo "========================================"
echo "Job Control CLI Commands - Verification"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "Project: bop (Rust workspace)"
echo "Task: Verify retry/kill/logs commands"
echo ""

# ============================================
# ENVIRONMENT CHECKS
# ============================================

echo "Checking environment..."

# Check for Rust/Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found${NC}"
    echo "Please install Rust: https://rustup.rs/"
    exit 1
fi

echo -e "${GREEN}✓ cargo found: $(cargo --version)${NC}"

# Check for Make
if ! command -v make &> /dev/null; then
    echo -e "${YELLOW}WARNING: make not found${NC}"
    echo "make check will not work without it"
else
    echo -e "${GREEN}✓ make found${NC}"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."
cargo build --release

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# VERIFY COMMANDS EXIST
# ============================================

echo ""
echo "Verifying commands exist..."

COMMANDS=("retry" "kill" "logs")
for cmd in "${COMMANDS[@]}"; do
    if cargo run --release -- --help 2>&1 | grep -q "$cmd"; then
        echo -e "${GREEN}✓ bop $cmd command exists${NC}"
    else
        echo -e "${RED}✗ bop $cmd command NOT FOUND${NC}"
        exit 1
    fi
done

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "All three commands are implemented:"
echo "  • bop retry <id>      - Move failed card to pending"
echo "  • bop kill <id>       - Send SIGTERM to running agent"
echo "  • bop logs <id>       - Stream stdout/stderr logs"
echo "  • bop logs <id> --follow - Tail live logs"
echo ""
echo "Next steps:"
echo "  1. Run: cargo test"
echo "  2. Run: make check"
echo "  3. Verify all acceptance criteria"
echo ""
