#!/bin/bash

# Auto-Build Environment Setup for spec 027
# AC implementation plan progress in Quick Look + CLI
# Generated by Planner Agent

set -e

echo "========================================"
echo "Spec 027: AC Progress in QL + CLI"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Rust toolchain
if ! command -v cargo &>/dev/null; then
    echo -e "${RED}cargo not found — install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}✓ cargo$(cargo --version | awk '{print " "$2}')${NC}"

# Nushell
if ! command -v nu &>/dev/null && ! [ -x /opt/homebrew/bin/nu ]; then
    echo -e "${YELLOW}⚠ nu not found — dispatch.nu changes won't be testable${NC}"
else
    NU_PATH=${NU_PATH:-$(command -v nu 2>/dev/null || echo /opt/homebrew/bin/nu)}
    echo -e "${GREEN}✓ nu $($NU_PATH --version 2>/dev/null || echo '(version unknown)')${NC}"
fi

# Xcode (for Quick Look build)
if command -v xcodebuild &>/dev/null; then
    XCODE_VER=$(xcodebuild -version 2>/dev/null | head -1 || echo "unknown")
    echo -e "${GREEN}✓ $XCODE_VER${NC}"
else
    echo -e "${YELLOW}⚠ xcodebuild not found — Quick Look changes won't build${NC}"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."
cargo build 2>&1

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ cargo build succeeded${NC}"
else
    echo -e "${RED}✗ cargo build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running tests..."
cargo test 2>&1

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ cargo test passed${NC}"
else
    echo -e "${RED}✗ cargo test failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Crates to modify:"
echo "  bop-core: crates/bop-core/src/lib.rs (Meta.ac_spec_id)"
echo "  bop-cli:  crates/bop-cli/src/acplan.rs (new), list.rs, render/*.rs"
echo "  macos:    macos/bop/PreviewViewController.swift (Plan tab)"
echo "  scripts:  dispatch.nu (card linkage)"
echo ""
echo "Verification: make check && xcodebuild ..."
echo ""
