#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 005-run-merge-gate

set -e

echo "========================================"
echo "Starting Merge-Gate Execution Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check for required tools
echo "Checking for required tools..."

if ! command -v cargo &> /dev/null; then
    echo -e "${RED}cargo not found. Please install Rust: https://rustup.rs/${NC}"
    exit 1
fi

if ! command -v rustc &> /dev/null; then
    echo -e "${RED}rustc not found. Please install Rust: https://rustup.rs/${NC}"
    exit 1
fi

echo -e "${GREEN}Rust toolchain found${NC}"
echo "  cargo: $(cargo --version)"
echo "  rustc: $(rustc --version)"

# Verify we're in the project root
if [ ! -f "Cargo.toml" ]; then
    echo -e "${RED}Cargo.toml not found. Are you in the project root?${NC}"
    exit 1
fi

if [ ! -d ".cards" ]; then
    echo -e "${RED}.cards directory not found${NC}"
    exit 1
fi

echo -e "${GREEN}Project structure verified${NC}"

# Check for cards in done/
DONE_COUNT=$(find .cards/team-arch/done .cards/team-quality/done -maxdepth 1 -type d -name "*.jobcard" 2>/dev/null | wc -l | tr -d ' ')
echo ""
echo "Found ${DONE_COUNT} cards in done/ directories"

if [ "$DONE_COUNT" -eq 0 ]; then
    echo -e "${YELLOW}Warning: No cards found in done/ directories${NC}"
    echo "This task expects cards to be present."
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "Working Directory: $(pwd)"
echo "Cards to process: ${DONE_COUNT}"
echo ""
echo "Next steps:"
echo "  1. cargo build"
echo "  2. ./target/debug/bop list --state done"
echo "  3. ./target/debug/bop merge-gate --once (loop)"
echo "  4. make check"
echo ""
