#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 008-shell-completions

set -e

echo "========================================"
echo "Shell Completions Build Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo "Checking prerequisites..."

# Check for cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found${NC}"
    echo "Please install Rust: https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ cargo found${NC}"

# Check for rustc
if ! command -v rustc &> /dev/null; then
    echo -e "${RED}Error: rustc not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ rustc found${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop CLI..."

cargo build --release

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Binary: ./target/release/bop"
echo ""
echo "Next steps:"
echo "  1. Rename GenerateCompletion to Completions in crates/bop-cli/src/main.rs"
echo "  2. Test: ./target/release/bop completions bash"
echo "  3. Run: make check"
echo ""
