use anyhow::Context;
use std::fs;
use std::path::Path;

pub fn cmd_index(cards_root: &Path, print_flag: bool) -> anyhow::Result<()> {
    // Resolve workspace root: parent of the .cards/ dir.
    // cards_root may be a relative path like ".cards"; canonicalize first.
    let cards_abs = cards_root
        .canonicalize()
        .unwrap_or_else(|_| cards_root.to_path_buf());
    let repo_root_owned = cards_abs
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| cards_abs.clone());
    let repo_root = repo_root_owned.as_path();

    let mut out = String::new();

    // ── 1. Header ────────────────────────────────────────────────────────────
    out.push_str("# Codebase Index\n\n");
    out.push_str("*Auto-generated by `bop index`. Read this before exploring files.*\n\n");

    // ── 2. Top-level layout ───────────────────────────────────────────────────
    out.push_str("## Top-level layout\n\n");
    let dir_descriptions: &[(&str, &str)] = &[
        (
            "crates/",
            "Rust workspace members (bop-core lib + bop-cli binary)",
        ),
        (
            ".cards/",
            "Job card state machine — pending/ running/ done/ merged/ failed/",
        ),
        (
            "adapters/",
            "Shell adapter scripts: claude.nu, mock.nu, timeout_wrapper.nu",
        ),
        (
            "scripts/",
            "Helper scripts: policy_check.nu and other tooling",
        ),
        ("layouts/", "Zellij terminal layout files (bop.kdl)"),
        (
            "macos/",
            "Xcode project for Quick Look extension (BopHost.app)",
        ),
        (
            "vibekanban/",
            "Zellij WASM plugin source for kanban pane display",
        ),
        ("completions/", "Shell completion scripts"),
        (
            "skills/",
            "Claude skill definitions (markdown prompts for agents)",
        ),
        ("docs/", "Project documentation"),
        ("research/", "Research notes and vendor snapshots"),
        ("examples/", "Example bop templates and usage"),
        ("launchd/", "macOS launchd service plists"),
        ("zellij/", "Zellij config and plugin assets"),
    ];
    for (dir, desc) in dir_descriptions {
        if repo_root.join(dir.trim_end_matches('/')).exists() {
            out.push_str(&format!("- **`{dir}`** — {desc}\n"));
        }
    }
    out.push('\n');

    // ── 3. Key files ─────────────────────────────────────────────────────────
    out.push_str("## Key files\n\n");
    let key_files: &[(&str, &str)] = &[
        (
            "Cargo.toml",
            "Workspace manifest; lists crate members and shared dependencies",
        ),
        (
            "Makefile",
            "Shortcuts: `make check` runs test + clippy + fmt",
        ),
        (
            "crates/bop-cli/src/main.rs",
            "CLI binary: all `bop` subcommands, dispatcher loop, merge-gate",
        ),
        (
            "crates/bop-core/src/lib.rs",
            "Shared types: Meta, PromptContext, render_prompt, VcsEngine",
        ),
        (
            ".cards/providers.json",
            "Provider registry with cooldowns and model config",
        ),
        (
            ".cards/system_context.md",
            "Agent orientation text prepended to every dispatched prompt",
        ),
        (
            ".cards/CODEBASE.md",
            "This file — concise codebase map for agent orientation",
        ),
        (
            ".cards/templates/",
            "COW-cloneable card templates (implement, qa, …)",
        ),
        (
            ".cards/stages/",
            "Per-stage instruction fragments injected via {{stage_instructions}}",
        ),
        (
            "adapters/claude.nu",
            "Production adapter: calls Claude Code CLI with timeout",
        ),
        (
            "adapters/mock.nu",
            "Testing adapter: writes stub output immediately",
        ),
        (
            "scripts/policy_check.nu",
            "Policy gate: checks staged files against rules",
        ),
    ];
    for (file, desc) in key_files {
        if repo_root.join(file).exists() {
            out.push_str(&format!("- `{file}` — {desc}\n"));
        }
    }
    out.push('\n');

    // ── 4. Crate map ─────────────────────────────────────────────────────────
    out.push_str("## Crate map\n\n");
    let cargo_toml_path = repo_root.join("Cargo.toml");
    if cargo_toml_path.exists() {
        let cargo_contents = fs::read_to_string(&cargo_toml_path).unwrap_or_default();
        let mut members: Vec<String> = Vec::new();
        let mut in_members = false;
        for line in cargo_contents.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("members") && trimmed.contains('[') {
                in_members = true;
            }
            if in_members {
                let mut parts = trimmed.split('"');
                parts.next();
                while let (Some(member), Some(_)) = (parts.next(), parts.next()) {
                    if !member.is_empty() && !member.starts_with('#') {
                        members.push(member.to_string());
                    }
                }
                if trimmed.contains(']') {
                    in_members = false;
                }
            }
        }

        for member in &members {
            let crate_dir = repo_root.join(member);
            let crate_cargo = crate_dir.join("Cargo.toml");
            let crate_name = if crate_cargo.exists() {
                fs::read_to_string(&crate_cargo)
                    .ok()
                    .and_then(|s| {
                        s.lines()
                            .find(|l| l.starts_with("name"))
                            .and_then(|l| l.split('"').nth(1))
                            .map(String::from)
                    })
                    .unwrap_or_else(|| member.clone())
            } else {
                member.clone()
            };

            out.push_str(&format!("### `{crate_name}` (`{member}/`)\n\n"));

            let src_file = if crate_dir.join("src/lib.rs").exists() {
                crate_dir.join("src/lib.rs")
            } else {
                crate_dir.join("src/main.rs")
            };

            if src_file.exists() {
                let header: String = fs::read_to_string(&src_file)
                    .unwrap_or_default()
                    .lines()
                    .take(60)
                    .collect::<Vec<_>>()
                    .join("\n");

                let public_items: Vec<&str> = header
                    .lines()
                    .filter(|l| {
                        let t = l.trim();
                        (t.starts_with("pub struct ")
                            || t.starts_with("pub enum ")
                            || t.starts_with("pub fn ")
                            || t.starts_with("pub async fn "))
                            && !t.contains("//")
                    })
                    .collect();

                if !public_items.is_empty() {
                    out.push_str("Public API (first 60 lines):\n");
                    for item in public_items.iter().take(12) {
                        let sig = item.trim().trim_end_matches('{').trim();
                        out.push_str(&format!("- `{sig}`\n"));
                    }
                    out.push('\n');
                } else {
                    let docs: String = header
                        .lines()
                        .filter(|l| l.trim().starts_with("///") || l.trim().starts_with("//!"))
                        .take(5)
                        .collect::<Vec<_>>()
                        .join("\n");
                    if !docs.is_empty() {
                        out.push_str(&format!("```\n{docs}\n```\n\n"));
                    }
                }
            }
        }
    }

    // ── 5. Common patterns ────────────────────────────────────────────────────
    out.push_str("## Common patterns\n\n");
    out.push_str("- **State transitions** are atomic `fs::rename` calls: `pending/` → `running/` → `done/` → `merged/` (or `failed/`)\n");
    out.push_str("- **Cards** are `<id>.bop/` directory bundles: `meta.json`, `spec.md`, `prompt.md`, `logs/`, `output/`\n");
    out.push_str("- **`bop new <template> <id>`** COW-clones a template and writes `meta.json`\n");
    out.push_str("- **Adapters** are shell scripts called as `adapter.sh <workdir> <prompt> <stdout> <stderr> [timeout]`; exit 75 = rate-limited\n");
    out.push_str("- **Provider failover**: on exit 75 the provider chain rotates and a 300s cooldown is set in `providers.json`\n");
    out.push_str("- **VCS**: jj (Jujutsu) for multi-agent sessions; each agent gets an isolated `jj workspace`\n");
    out.push_str("- **`{{spec}}`, `{{plan}}`, `{{stage_instructions}}`** — template substitution keys in prompt templates\n");
    out.push_str(
        "- **`make check`** = `cargo test && cargo clippy -- -D warnings && cargo fmt --check`\n",
    );

    // ── Output ────────────────────────────────────────────────────────────────
    if print_flag {
        print!("{out}");
    } else {
        let dest = cards_root.join("CODEBASE.md");
        fs::write(&dest, &out).with_context(|| format!("failed to write {}", dest.display()))?;
        println!("wrote {}", dest.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn cmd_index_print_mode_no_error() {
        let td = tempdir().unwrap();
        // print=true should output to stdout without error
        cmd_index(td.path(), true).unwrap();
    }

    #[test]
    fn cmd_index_write_mode_creates_file() {
        let td = tempdir().unwrap();
        cmd_index(td.path(), false).unwrap();
        let dest = td.path().join("CODEBASE.md");
        assert!(dest.exists());
        let content = fs::read_to_string(&dest).unwrap();
        assert!(content.contains("# Codebase Index"));
        assert!(content.contains("Auto-generated by `bop index`"));
    }

    #[test]
    fn cmd_index_output_contains_common_patterns() {
        let td = tempdir().unwrap();
        cmd_index(td.path(), false).unwrap();
        let content = fs::read_to_string(td.path().join("CODEBASE.md")).unwrap();
        assert!(content.contains("## Common patterns"));
        assert!(content.contains("State transitions"));
    }
}
