#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Rust toolchain
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: cargo not found. Please install Rust: https://rustup.rs${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain available${NC}"

# Check we're in the bop project
if [ ! -f "Cargo.toml" ] || ! grep -q 'members.*bop-cli' Cargo.toml 2>/dev/null; then
    echo -e "${RED}Error: Not in bop project root${NC}"
    exit 1
fi
echo -e "${GREEN}✓ In bop project root${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop..."
cargo build

if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Build complete${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Development commands:"
echo "  cargo build                    # Build the project"
echo "  cargo test                     # Run tests"
echo "  make check                     # Run full quality checks"
echo "  ./target/debug/bop --help      # Run bop CLI"
echo ""
echo "For this spec (021):"
echo "  ./target/debug/bop init        # Test init command"
echo "  ./target/debug/bop doctor      # Test doctor command"
echo ""
