#!/bin/bash

# Auto-Build Environment Setup — Spec 028: Terminal Card Renderer
# Generated by Planner Agent

set -e

echo "========================================"
echo "Spec 028: Terminal Card Renderer"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY TOOLCHAIN
# ============================================

echo ""
echo "Checking toolchain..."

# Rust toolchain
if command -v cargo >/dev/null 2>&1; then
    RUST_VER=$(rustc --version)
    echo -e "${GREEN}✓ Rust: ${RUST_VER}${NC}"
else
    echo -e "${RED}✗ Rust not found — install via rustup${NC}"
    exit 1
fi

# Clippy
if cargo clippy --version >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Clippy available${NC}"
else
    echo -e "${YELLOW}⚠ Clippy not found — install: rustup component add clippy${NC}"
fi

# Rustfmt
if cargo fmt --version >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Rustfmt available${NC}"
else
    echo -e "${YELLOW}⚠ Rustfmt not found — install: rustup component add rustfmt${NC}"
fi

# Python3 (for vibekanban provider)
if command -v python3 >/dev/null 2>&1; then
    PY_VER=$(python3 --version)
    echo -e "${GREEN}✓ Python: ${PY_VER}${NC}"
else
    echo -e "${YELLOW}⚠ Python3 not found — vibekanban provider update won't be testable${NC}"
fi

# ============================================
# BUILD CHECK
# ============================================

echo ""
echo "Running initial build check..."

cd /Users/studio/bop

if cargo check -p bop 2>&1; then
    echo -e "${GREEN}✓ Workspace compiles${NC}"
else
    echo -e "${RED}✗ Build failed — fix errors before starting${NC}"
    exit 1
fi

# ============================================
# VERIFY CARDS LAYOUT
# ============================================

echo ""
if [ -d ".cards" ]; then
    echo -e "${GREEN}✓ .cards/ directory exists${NC}"
else
    echo -e "${YELLOW}⚠ .cards/ not found — run 'bop init' if needed for integration testing${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: /Users/studio/bop"
echo "Crate:   crates/bop-cli (bop binary)"
echo ""
echo "New files to create:"
echo "  crates/bop-cli/src/termcaps.rs"
echo "  crates/bop-cli/src/render/mod.rs"
echo "  crates/bop-cli/src/render/dumb.rs"
echo "  crates/bop-cli/src/render/basic.rs"
echo "  crates/bop-cli/src/render/extended.rs"
echo "  crates/bop-cli/src/render/full.rs"
echo "  crates/bop-cli/src/render/truecolor.rs"
echo ""
echo "Files to modify:"
echo "  crates/bop-cli/Cargo.toml (add terminal_size)"
echo "  crates/bop-cli/src/main.rs (register modules)"
echo "  crates/bop-cli/src/list.rs (wire renderers)"
echo "  vibekanban/_bop_provider_impl.py (add fields)"
echo ""
echo "Verification: make check (cargo test + clippy + fmt)"
echo ""
