#!/bin/bash

# Auto-Build Environment Setup — Spec 032 (Ollama + OpenCode Providers)
# Generated by Planner Agent

set -e

echo "========================================"
echo "Spec 032: Ollama + OpenCode Providers"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

cd /Users/studio/bop

# ============================================
# VERIFY BUILD ENVIRONMENT
# ============================================

echo ""
echo "Checking Rust toolchain..."
if ! command -v cargo &>/dev/null; then
    echo -e "${RED}cargo not found — install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}cargo: $(cargo --version)${NC}"

echo ""
echo "Checking initial build..."
if cargo build -p bop 2>&1; then
    echo -e "${GREEN}Build OK${NC}"
else
    echo -e "${RED}Build failed — fix compilation errors before proceeding${NC}"
    exit 1
fi

echo ""
echo "Running existing tests..."
if cargo test -p bop 2>&1; then
    echo -e "${GREEN}Tests pass${NC}"
else
    echo -e "${YELLOW}Some tests failed — check output above${NC}"
fi

echo ""
echo "Checking clippy..."
if cargo clippy -p bop -- -D warnings 2>&1; then
    echo -e "${GREEN}Clippy clean${NC}"
else
    echo -e "${YELLOW}Clippy warnings — check output above${NC}"
fi

# ============================================
# VERIFY KEY FILES EXIST
# ============================================

echo ""
echo "Verifying provider module structure..."

for f in \
    crates/bop-cli/src/providers/mod.rs \
    crates/bop-cli/src/providers/claude.rs \
    crates/bop-cli/src/providers/codex.rs \
    crates/bop-cli/src/providers/gemini.rs \
    crates/bop-cli/src/providers/history.rs \
    crates/bop-cli/Cargo.toml; do
    if [ -f "$f" ]; then
        echo -e "  ${GREEN}✓${NC} $f"
    else
        echo -e "  ${RED}✗${NC} $f (MISSING)"
    fi
done

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: /Users/studio/bop"
echo "Crate:   bop (crates/bop-cli/)"
echo ""
echo "Files to create:"
echo "  crates/bop-cli/src/providers/ollama.rs"
echo "  crates/bop-cli/src/providers/opencode.rs"
echo ""
echo "Files to modify:"
echo "  crates/bop-cli/src/providers/mod.rs"
echo ""
echo "Pattern references:"
echo "  crates/bop-cli/src/providers/claude.rs"
echo "  crates/bop-cli/src/providers/codex.rs"
echo ""
