#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 022

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 022-atomic-write-meta-crash-recovery"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Rust toolchain
echo "Checking Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Cargo not found. Please install Rust toolchain.${NC}"
    exit 1
fi
echo -e "${GREEN}Cargo found: $(cargo --version)${NC}"

# Check formatting tools
echo "Checking rustfmt..."
if ! command -v rustfmt &> /dev/null; then
    echo -e "${YELLOW}rustfmt not found. Installing...${NC}"
    rustup component add rustfmt
fi
echo -e "${GREEN}rustfmt ready${NC}"

# Check clippy
echo "Checking clippy..."
if ! cargo clippy --version &> /dev/null; then
    echo -e "${YELLOW}clippy not found. Installing...${NC}"
    rustup component add clippy
fi
echo -e "${GREEN}clippy ready${NC}"

# Build project
echo ""
echo "Building project..."
cargo build
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "Binary: ./target/debug/bop"
echo ""
echo "Available commands:"
echo "  make check  - Run all checks (test + clippy + fmt)"
echo "  make test   - Run tests only"
echo "  make lint   - Run clippy only"
echo "  cargo build - Build the project"
echo ""
echo "Implementation ready to begin!"
echo ""
