#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 024-sleep-wake-network-resilience

set -e

echo "========================================"
echo "Sleep/Wake Network Resilience - Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo "Verifying Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found. Install Rust from https://rustup.rs${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain found${NC}"

echo "Verifying Nushell..."
if ! command -v nu &> /dev/null; then
    echo -e "${RED}ERROR: nu not found. Install Nushell from https://nushell.sh${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Nushell found${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop project..."
cargo build -p bop
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running existing tests..."
cargo test --lib
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Tests passed${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed (may be expected before implementation)${NC}"
fi

# ============================================
# VERIFY ADAPTER SCRIPTS
# ============================================

echo ""
echo "Verifying adapter scripts..."
if [ -f "adapters/claude.nu" ]; then
    echo -e "${GREEN}✓ claude.nu found${NC}"
else
    echo -e "${RED}✗ claude.nu missing${NC}"
fi

if [ -f "adapters/codex.nu" ]; then
    echo -e "${GREEN}✓ codex.nu found${NC}"
else
    echo -e "${RED}✗ codex.nu missing${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "  Location: $(pwd)"
echo "  Binary: target/debug/bop"
echo ""
echo "Next steps:"
echo "  1. Review implementation_plan.json"
echo "  2. Start with phase-1-power-watcher"
echo "  3. Run 'make check' after each phase"
echo ""
echo "Platform-specific notes:"
echo "  - macOS: IOKit power watcher will be implemented"
echo "  - Linux: D-Bus logind stub (or zbus if feasible)"
echo "  - Other: No-op stubs"
echo ""
