#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 023

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# RUST PROJECT SETUP
# ============================================

echo ""
echo "Checking Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}cargo not found - please install Rust${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Rust toolchain ready${NC}"

echo ""
echo "Checking Nushell..."
if ! command -v nu &> /dev/null; then
    echo -e "${YELLOW}⚠ nushell not found - scripts may not work${NC}"
else
    echo -e "${GREEN}✓ Nushell ready${NC}"
fi

echo ""
echo "Building bop workspace..."
cargo build --workspace
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: bop (Rust workspace)"
echo "Binary: target/debug/bop"
echo ""
echo "Quick start:"
echo "  cargo build         # Build the project"
echo "  cargo test          # Run tests"
echo "  cargo clippy        # Lint"
echo "  make check          # Full CI check"
echo ""
echo "Commands to implement:"
echo "  bop pause           # Stop running adapters"
echo "  bop resume          # Resume paused cards"
echo "  bop retry-transient # Retry transient failures"
echo ""
