#!/bin/bash

# Auto-Build Environment Setup — spec 029 (bop ui TUI)
# Generated by Planner Agent

set -e

echo "========================================"
echo "  bop ui TUI — Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_DIR="/Users/studio/bop"

# ============================================
# VERIFY TOOLCHAIN
# ============================================

echo ""
echo "Checking toolchain..."

# Rust / Cargo
if ! command -v cargo &>/dev/null; then
    echo -e "${RED}cargo not found — install Rust via rustup${NC}"
    exit 1
fi
echo -e "${GREEN}✓ cargo $(cargo --version | awk '{print $2}')${NC}"

# Make
if ! command -v make &>/dev/null; then
    echo -e "${RED}make not found${NC}"
    exit 1
fi
echo -e "${GREEN}✓ make available${NC}"

# jj (Jujutsu VCS)
if ! command -v jj &>/dev/null; then
    echo -e "${YELLOW}⚠ jj not found — VCS operations will use git fallback${NC}"
else
    echo -e "${GREEN}✓ jj $(jj --version 2>/dev/null | head -1)${NC}"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."
cd "$PROJECT_DIR"

cargo build -p bop 2>&1 | tail -5
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ cargo build succeeded${NC}"
else
    echo -e "${RED}cargo build failed${NC}"
    exit 1
fi

# ============================================
# RUN TESTS
# ============================================

echo ""
echo "Running existing tests..."

cargo test -p bop 2>&1 | tail -10
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ cargo test passed${NC}"
else
    echo -e "${YELLOW}⚠ Some tests failed — review before implementing${NC}"
fi

# ============================================
# VERIFY CARDS STRUCTURE
# ============================================

echo ""
echo "Checking .cards/ layout..."

CARDS_DIR="$PROJECT_DIR/.cards"
if [ -d "$CARDS_DIR" ]; then
    for state in pending running done failed merged; do
        if [ -d "$CARDS_DIR/$state" ]; then
            count=$(ls -d "$CARDS_DIR/$state"/*.bop 2>/dev/null | wc -l | tr -d ' ')
            echo "  $state/: $count cards"
        else
            echo "  $state/: (missing)"
        fi
    done
    echo -e "${GREEN}✓ .cards/ structure found${NC}"
else
    echo -e "${YELLOW}⚠ .cards/ not found — run 'bop init' first${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "  Environment Ready!"
echo "========================================"
echo ""
echo "Project: $PROJECT_DIR"
echo "Binary:  target/debug/bop"
echo ""
echo "Key commands:"
echo "  cargo build -p bop          # build bop-cli"
echo "  cargo test -p bop           # run tests"
echo "  make check                  # test + clippy + fmt"
echo "  ./target/debug/bop ui       # run TUI (after implementing)"
echo ""
echo "New dependencies to add:"
echo "  ratatui = \"0.29\"            # TUI framework"
echo "  crossterm = \"0.28\"          # terminal backend"
echo "  nucleo = \"0.5\"              # fuzzy matcher"
echo "  insta (dev-dep)             # snapshot testing"
echo ""
