#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 016

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# BUILD BOP BINARY
# ============================================

echo "Building bop binary..."
cd /Users/studio/bop
cargo build

if [ ! -f "target/debug/bop" ]; then
    echo -e "${RED}ERROR: bop binary not found after build${NC}"
    exit 1
fi

echo -e "${GREEN}bop binary ready${NC}"

# ============================================
# VERIFY NUSHELL AVAILABLE
# ============================================

if ! command -v nu &> /dev/null; then
    echo -e "${RED}ERROR: nu (Nushell) not found in PATH${NC}"
    echo "Expected at /opt/homebrew/bin/nu"
    exit 1
fi

echo -e "${GREEN}Nushell available: $(which nu)${NC}"

# ============================================
# VERIFY CLAUDE CLI AVAILABLE
# ============================================

if ! command -v claude &> /dev/null; then
    echo -e "${YELLOW}WARNING: claude CLI not found in PATH${NC}"
    echo "The claude adapter test may fail if claude CLI is not installed"
fi

echo -e "${GREEN}Claude CLI available: $(which claude)${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Tools verified:"
echo "  - Rust/Cargo: $(rustc --version)"
echo "  - Nushell:    $(nu --version)"
echo "  - Claude CLI: $(claude --version 2>/dev/null || echo 'not found')"
echo ""
echo "Ready to run:"
echo "  nu --no-config-file scripts/test-real-adapters.nu --adapter claude --timeout 120"
echo ""
