#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 010-factory-watchpaths

set -e

echo "========================================"
echo "bop Factory WatchPaths Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop workspace..."
cargo build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Development Environment Ready!"
echo "========================================"
echo ""
echo "Binary: ./target/debug/bop"
echo ""
echo "To test the factory changes:"
echo "  1. Install factory services:"
echo "       ./target/debug/bop factory install"
echo ""
echo "  2. Check generated plists:"
echo "       cat ~/Library/LaunchAgents/sh.bop.dispatcher.plist"
echo "       grep -A5 WatchPaths ~/Library/LaunchAgents/sh.bop.*.plist"
echo ""
echo "  3. Check service status:"
echo "       ./target/debug/bop factory status"
echo ""
echo "  4. Manual trigger test:"
echo "       touch .cards/pending/test-card.txt"
echo "       tail -f /tmp/bop-dispatcher.log"
echo ""
echo "  5. Run tests:"
echo "       make check"
echo ""
echo "To uninstall services:"
echo "  ./target/debug/bop factory uninstall"
echo ""
