#!/bin/bash

# Auto-Build Environment Setup — Spec 031: Codex + Gemini Providers
# Generated by Planner Agent

set -e

echo "========================================"
echo "Spec 031: Codex + Gemini Providers"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/Users/studio/bop"

# ============================================
# VERIFY BUILD ENVIRONMENT
# ============================================

echo "Checking Rust toolchain..."
if ! command -v cargo &>/dev/null; then
    echo -e "${RED}cargo not found — install Rust toolchain${NC}"
    exit 1
fi
echo -e "${GREEN}cargo $(cargo --version | cut -d' ' -f2) found${NC}"

echo ""
echo "Checking workspace builds..."
cd "$PROJECT_ROOT"
if cargo check -p bop 2>&1 | tail -1 | grep -q "error"; then
    echo -e "${RED}cargo check -p bop failed — fix existing errors first${NC}"
    exit 1
fi
echo -e "${GREEN}Workspace compiles cleanly${NC}"

# ============================================
# VERIFY PATTERN FILES EXIST
# ============================================

echo ""
echo "Verifying reference files..."

for f in \
    "crates/bop-cli/src/providers/mod.rs" \
    "crates/bop-cli/src/providers/claude.rs" \
    "crates/bop-cli/src/providers/history.rs" \
    "crates/bop-cli/Cargo.toml"; do
    if [ -f "$PROJECT_ROOT/$f" ]; then
        echo -e "  ${GREEN}✓${NC} $f"
    else
        echo -e "  ${RED}✗${NC} $f — MISSING"
        exit 1
    fi
done

# ============================================
# CHECK EXISTING TESTS PASS
# ============================================

echo ""
echo "Running existing provider tests..."
cd "$PROJECT_ROOT"
if cargo test -p bop -- providers:: --no-fail-fast 2>&1 | tail -1 | grep -q "FAILED"; then
    echo -e "${RED}Existing provider tests are failing — fix before starting${NC}"
    exit 1
fi
echo -e "${GREEN}All existing provider tests pass${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: $PROJECT_ROOT"
echo "Crate:   bop-cli (crates/bop-cli/)"
echo ""
echo "Files to create:"
echo "  crates/bop-cli/src/providers/codex.rs"
echo "  crates/bop-cli/src/providers/gemini.rs"
echo ""
echo "Files to modify:"
echo "  crates/bop-cli/src/providers/mod.rs"
echo ""
echo "Commands:"
echo "  Build:  cargo build -p bop"
echo "  Test:   cargo test -p bop -- providers::"
echo "  Clippy: cargo clippy -p bop -- -D warnings"
echo "  Fmt:    cargo fmt -p bop -- --check"
echo ""
