#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 025

set -e

echo "========================================"
echo "bop status --watch - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY RUST TOOLCHAIN
# ============================================

echo ""
echo "Checking Rust toolchain..."
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}ERROR: cargo not found${NC}"
    echo "Install Rust from https://rustup.rs/"
    exit 1
fi
echo -e "${GREEN}✓ cargo found${NC}"

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building bop CLI..."
cargo build --quiet
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# VERIFY BINARY
# ============================================

echo ""
echo "Verifying bop binary..."
if [ -f "./target/debug/bop" ]; then
    echo -e "${GREEN}✓ Binary exists at ./target/debug/bop${NC}"
else
    echo -e "${RED}✗ Binary not found${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Implement --watch flag: crates/bop-cli/src/main.rs"
echo "  2. Add watch loop: crates/bop-cli/src/list.rs"
echo "  3. Test: ./target/debug/bop status --watch"
echo ""
echo "Development commands:"
echo "  cargo build          # Build project"
echo "  cargo test           # Run tests"
echo "  make check           # Run all checks (test + clippy + fmt)"
echo ""
